language: php
php:
  - '5.6'
matrix:
  fast_finish: true
sudo: required
before_install:
  - sudo apt-get update > /dev/null
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit
branches:
  only:
    - master
